### ISSUE TITLE
Fetch API cannot load http://www.graphqlhub.com/graphql.

### ISSUE THREAD

**Issue by car3oon** [clayallsopp/relay-101#5]
Hello 
I want to thank you for great tutorial at the beginning.

I've cloned your repo and sadly i'm getting some errors in console:

```
Fetch API cannot load http://www.graphqlhub.com/graphql. Response for preflight is invalid (redirect)
Failed to fetch
   _markAsRejected
   _handleSubtractedQueryFailure
   tryCallOne
   (anonymous function)
   flush
```

Maybe you have some clues what might went wrong. Thanks in advance.
Other question is did you try to updates packages ?

**Comment by clayallsopp** [comment]
@car3oon can you pull and try again? The URLs were outdated, needed to be HTTPS

**Comment by car3oon** [comment]
Thank you for quick response @clayallsopp 

After fresh pull and `npm install` i have this error:

```
$ npm start

> relay-101@1.0.0 start /home/lwegiel/Workspaces/relay-101
> webpack-dev-server

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at net.js:1381:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Linux 4.2.0-36-generic
npm ERR! argv "/home/lwegiel/.nvm/versions/node/v5.5.0/bin/node" "/home/lwegiel/.nvm/versions/node/v5.5.0/bin/npm" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! relay-101@1.0.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the relay-101@1.0.0 start script 'webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the relay-101 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls relay-101
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lwegiel/Workspaces/relay-101/npm-debug.log
```

after `npm start`

Which version of node.js and npm do you have ?

**Comment by clayallsopp** [comment]
@car3oon `EADDRINUSE 127.0.0.1:8080` means that you're already running a server (either for this repo or another project) on port 8080 - make sure you kill that server or change the port for this one, i.e. `./node_modules/.bin/webpack-dev-server --port 8081`

**Comment by car3oon** [comment]
Now that works like a charm :+1: 
Thank you @clayallsopp
